# Generated by Django 3.2.6 on 2024-04-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='refresh_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
