FROM python:3.11

WORKDIR /code

RUN pip install --upgrade pip
RUN pip install celery
RUN pip install redis
COPY ./requirements.txt /code/requirements.txt
RUN pip install -r /code/requirements.txt

COPY . .

ENV C_FORCE_ROOT=true

CMD celery -A django_avito worker --loglevel=info
