# Generated by Django 4.2.7 on 2024-05-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrights',
            name='user_crm_id',
            field=models.CharField(max_length=100),
        ),
    ]
